version: '3'

services:
  app:
    build: .
    volumes:
      - .:/code
    command: celery -A task.tasks worker --loglevel=INFO
    tty: true
    stdin_open: true
    depends_on:
      - redis

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"